### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by fincardona** [billydh/python-avro-producer#1]
Hi @billydh,
Thank you for your tutorial on consuming and producing Avro records to a Kafka topic in Python environment: I found it very useful!  
Unfortunately, when I run your scripts, I get the following error message: 
```
Exception while producing record value - {'email': 'email@email.com', 'firstName': 'Bob', 'lastName': 'Jones'} to topic - create-user-request: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /subjects/create-user-request-value/versions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9b48668a90>: Failed to establish a new connection: [Errno 111] Connection refused')) 
```
Do you know why?

Thanks.

Federico

**Comment by billydh** [comment]
Hi @fincardona thanks for visiting and following the tutorial.

The exception indicates there's a problem with connecting to the Schema Registry at port 8081.

Can you share with me the command you executed when you received the exception?
How did you spin up the Schema Registry?
Did you change any of the avro producer code compared to the one in the tutorial?

**Comment by fincardona** [comment]
Yes, I originally did some changes to adapt your code to my script. However, as a double-check, I cloned your repository in my home, I created the virtual environment, I installed the requirements (```pip install -r requirements.txt```), and then I executed: ``` python send_record.py --topic create-user-request --schema-file create-user-request.avsc --record-value '{"email": "email@email.com", "firstName": "Bob", "lastName": "Jones"}' ``` but, unfortunately, I got the same error message.

**Comment by billydh** [comment]
hi @fincardona, just checking, did you miss the step to spin up the Schema Registry and Kafka containers as outlined in this [tutorial](https://medium.com/better-programming/your-local-event-driven-environment-using-dockerised-kafka-cluster-6e84af09cd95?source=friends_link&sk=6d4b3f1e16b0f56f721fcf4cc048dcfc) and [this](https://medium.com/better-programming/adding-schema-registry-to-kafka-in-your-local-docker-environment-49ada28c8a9b) (both tutorials are referenced in the [tutorial](https://medium.com/better-programming/avro-producer-with-python-and-confluent-kafka-library-4a1a2ed91a24) for avro producer)?

**Comment by fincardona** [comment]
That's it! Thanks! I actually missed those tutorials; sorry for that, and thanks again for your help!
